### ISSUE TITLE
Backend python flask server with login

### ISSUE THREAD

**Issue by jbakerforsberg** [ForsbergServices/apm-application#14]
Write the preliminary python backend which can handle user logins. This will also form the basis for HTTP requests with the front end.

**Comment by NathanJRDaniels** [comment]
the commit needs testing (forgot to link it oops)

**Comment by NathanJRDaniels** [comment]
adding the whole cyberSec to this ticket :)

**Comment by NathanJRDaniels** [comment]
lol no. even I can't write a fully secure website in < an afternoon from scratch

**Comment by NathanJRDaniels** [comment]
#24 done?
